//go:build darwin

package kernel

import (
	"encoding/binary"
	"errors"
	"fmt"
	"net"
	"os"
	"os/exec"
	"strings"
	"syscall"
	"unsafe"
)

// anchorName is the pf anchor we own. All our rules live inside this anchor
// so they don't conflict with user-managed rules.
const anchorName = "egress-guard"

// anchorFilePath is where we write the anchor's rule set.
const anchorFilePath = "/etc/pf.anchors/egress-guard"

type pfDarwin struct{}

func defaultInstaller() RulesInstaller { return &pfDarwin{} }

// buildAnchorRules renders the anchor's rule text. Extracted from Install so
// tests can verify the generated rules without writing to /etc/pf.anchors or
// invoking pfctl.
func buildAnchorRules(redirectPort int) string {
	return fmt.Sprintf(
		"# auto-generated by egress-guard -- do not edit\n"+
			"rdr pass on lo0 inet proto tcp from any to any port 443 -> 127.0.0.1 port %d\n"+
			"rdr pass inet proto tcp from any to any port 443 -> 127.0.0.1 port %d\n",
		redirectPort, redirectPort,
	)
}

func (p *pfDarwin) Install(redirectPort int) error {
	rules := buildAnchorRules(redirectPort)
	if err := os.WriteFile(anchorFilePath, []byte(rules), 0o644); err != nil {
		return fmt.Errorf("kernel: write anchor: %w", err)
	}
	cmd := exec.Command("pfctl", "-a", anchorName, "-f", anchorFilePath)
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("kernel: pfctl -f: %w (output: %s)", err, out)
	}
	cmd = exec.Command("pfctl", "-E")
	_ = cmd.Run()
	return nil
}

func (p *pfDarwin) Uninstall() error {
	cmd := exec.Command("pfctl", "-a", anchorName, "-F", "all")
	out, err := cmd.CombinedOutput()
	if err != nil && !strings.Contains(string(out), "No such anchor") {
		return fmt.Errorf("kernel: pfctl -F: %w (output: %s)", err, out)
	}
	if err := os.Remove(anchorFilePath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("kernel: remove anchor file: %w", err)
	}
	return nil
}

func (p *pfDarwin) IsInstalled() (bool, error) {
	if _, err := os.Stat(anchorFilePath); err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	cmd := exec.Command("pfctl", "-a", anchorName, "-sn")
	out, err := cmd.CombinedOutput()
	if err != nil {
		if strings.Contains(string(out), "No such anchor") {
			return false, nil
		}
		return false, fmt.Errorf("kernel: pfctl -sn: %w", err)
	}
	return strings.Contains(string(out), "rdr"), nil
}

// pfNatLook mirrors `struct pfioc_natlook` from <net/pfvar.h> on darwin.
// We hardcode the layout because cgo-free is preferable for a security daemon.
//
// Reference: https://opensource.apple.com/source/xnu/xnu-7195.50.7.100.1/bsd/net/pfvar.h
type pfNatLook struct {
	saddr     [16]byte // union: sockaddr_in / sockaddr_in6 padding
	daddr     [16]byte
	rsaddr    [16]byte // post-rdr replacement saddr
	rdaddr    [16]byte // post-rdr replacement daddr (= our local listen addr)
	sxport    uint16
	dxport    uint16
	rsxport   uint16
	rdxport   uint16
	af        uint8
	proto     uint8
	protoVar  uint8
	direction uint8
}

const (
	pfIn  uint8 = 1
	pfOut uint8 = 2
)

// diocNatlook computes the DIOCNATLOOK ioctl number:
//
//	_IOWR('D', 23, struct pfioc_natlook)
//
// macOS encoding: in/out (0xc0), size in low 13 bits of high half-word,
// group ('D' = 0x44), command (23).
func diocNatlook() uintptr {
	const (
		iocOut   uintptr = 0x40000000
		iocIn    uintptr = 0x80000000
		iocInOut         = iocIn | iocOut
	)
	size := uintptr(unsafe.Sizeof(pfNatLook{})) & 0x1fff
	return iocInOut | (size << 16) | (uintptr('D') << 8) | 23
}

// OriginalDest queries pf NAT state for the connection's pre-redirect destination.
func (p *pfDarwin) OriginalDest(conn net.Conn) (net.IP, int, error) {
	tcp, ok := conn.(*net.TCPConn)
	if !ok {
		return nil, 0, errors.New("kernel: OriginalDest expects *net.TCPConn")
	}
	rAddr, _ := tcp.RemoteAddr().(*net.TCPAddr)
	lAddr, _ := tcp.LocalAddr().(*net.TCPAddr)
	if rAddr == nil || lAddr == nil {
		return nil, 0, errors.New("kernel: TCPConn missing addresses")
	}

	dev, err := os.OpenFile("/dev/pf", os.O_RDWR, 0)
	if err != nil {
		return nil, 0, fmt.Errorf("kernel: open /dev/pf: %w", err)
	}
	defer dev.Close()

	var nl pfNatLook
	nl.af = syscall.AF_INET
	nl.proto = syscall.IPPROTO_TCP
	nl.direction = pfOut
	if v4 := rAddr.IP.To4(); v4 != nil {
		copy(nl.saddr[:4], v4)
	}
	if v4 := lAddr.IP.To4(); v4 != nil {
		copy(nl.daddr[:4], v4)
	}
	binary.BigEndian.PutUint16(asBytes(&nl.sxport), uint16(rAddr.Port))
	binary.BigEndian.PutUint16(asBytes(&nl.dxport), uint16(lAddr.Port))

	_, _, errno := syscall.Syscall(
		syscall.SYS_IOCTL,
		uintptr(dev.Fd()),
		diocNatlook(),
		uintptr(unsafe.Pointer(&nl)),
	)
	if errno != 0 {
		return nil, 0, fmt.Errorf("kernel: DIOCNATLOOK: %w", errno)
	}
	ip := sockaddrToIP([4]byte{nl.rdaddr[0], nl.rdaddr[1], nl.rdaddr[2], nl.rdaddr[3]})
	port := int(binary.BigEndian.Uint16(asBytes(&nl.rdxport)))
	return ip, port, nil
}

// sockaddrToIP returns a net.IP from a 4-byte network-order array.
func sockaddrToIP(b [4]byte) net.IP {
	return net.IPv4(b[0], b[1], b[2], b[3])
}

// asBytes is an unsafe view of a uint16 as a 2-byte slice for binary.BigEndian.
func asBytes(p *uint16) []byte {
	return (*[2]byte)(unsafe.Pointer(p))[:]
}
