// Package catalogbuild compiles the public catalog fragments into the
// distributable known-good catalog files consumed by egress-guard.
package catalogbuild

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"github.com/byliu-labs/egress-guard/internal/catalog"
	"github.com/byliu-labs/egress-guard/internal/exempt"
)

// LoadBaselineDir reads every *.toml fragment in dir in sorted order and
// merges the validated fragments into a single catalog.
func LoadBaselineDir(dir string) (*catalog.Catalog, error) {
	paths, err := filepath.Glob(filepath.Join(dir, "*.toml"))
	if err != nil {
		return nil, err
	}
	sort.Strings(paths)

	live := &catalog.Catalog{}
	for _, p := range paths {
		c, err := catalog.LoadFile(p)
		if err != nil {
			return nil, err
		}
		live.Merge(c)
	}
	return live, nil
}

// CompileExempt concatenates every *.toml fragment in dir in sorted order and
// validates the result against the exempt-app schema before returning it.
func CompileExempt(dir string) ([]byte, error) {
	paths, err := filepath.Glob(filepath.Join(dir, "*.toml"))
	if err != nil {
		return nil, err
	}
	sort.Strings(paths)

	var buf bytes.Buffer
	buf.WriteString("# Generated by cmd/catalog-build from catalog/exempt/. Do not edit by hand.\n\n")
	for i, p := range paths {
		b, err := os.ReadFile(p)
		if err != nil {
			return nil, fmt.Errorf("catalogbuild: read exempt fragment %s: %w", p, err)
		}
		buf.Write(b)
		if i != len(paths)-1 {
			buf.WriteByte('\n')
		}
	}
	if _, err := exempt.LoadFromString(buf.String()); err != nil {
		return nil, fmt.Errorf("catalogbuild: compiled exempt catalog fails round-trip: %w", err)
	}
	return buf.Bytes(), nil
}

// CompileBaseline serializes an assembled known-good catalog and asserts that
// the bytes round-trip through catalog.Load before returning them.
func CompileBaseline(c *catalog.Catalog) ([]byte, error) {
	b, err := c.Marshal()
	if err != nil {
		return nil, fmt.Errorf("catalogbuild: marshal baseline: %w", err)
	}
	if _, err := catalog.Load(b); err != nil {
		return nil, fmt.Errorf("catalogbuild: compiled baseline fails round-trip: %w", err)
	}
	return b, nil
}
